version: "3.9"

services:
  max-contest-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: max-contest-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data

